Parameters:
  BucketNameParameter:
    Type: String

Resources:
  kyleshenklabsstelligent:
    Type: AWS::S3::Bucket
    Description: Basic AWS S3 Bucket Configuration
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${BucketNameParameter}'

